### warm up exercise

In [1]:
import pandas as pd

In [2]:
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
                'Mittal','Archana'],
                'Marks':[98,89,99,87,90,83,99],
                'Gender':['Male','Female','Female','Male','Male',
                         'Female','Female']
               }
df1=pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [3]:
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

In [4]:
df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [6]:
df1.isnull().sum(axis=1)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [7]:
df1.isnull().sum(axis=0)

Name      0
Marks     0
Gender    0
dtype: int64

In [8]:
df1.describe(include="all")

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

In [9]:
df1['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [10]:
df1['Gender'].nunique()

2

In [12]:
df1['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

In [18]:
len(df1[(df1['Marks']>=90) & (df1['Marks']<=100)])

4

In [21]:
len(df1[df1['Marks'].between(90,100)])

4

In [23]:
df1['Marks'].mean()

np.float64(92.14285714285714)

In [24]:
df1['Marks'].max()

np.int64(99)

In [25]:
df1['Marks'].min()

np.int64(83)

In [26]:
def marks(x):
  return x/2

In [28]:
df1['half-marks']=df1['Marks'].apply(marks)
df1

      Name  Marks  Gender  half-marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [29]:
df1['Marks'].apply(lambda x:x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [30]:
df1['Name'].apply(len)

0    7
1    6
2    6
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

In [32]:
df1['Male_female']=df1['Gender'].map({'male':1,'female':0})
df1

      Name  Marks  Gender  half-marks  Male_female
0  Priyang     98    Male        49.0          NaN
1   Aadhya     89  Female        44.5          NaN
2   Krisha     99  Female        49.5          NaN
3   Vedant     87    Male        43.5          NaN
4   Parshv     90    Male        45.0          NaN
5   Mittal     83  Female        41.5          NaN
6  Archana     99  Female        49.5          NaN

In [43]:
# df1.drop('Male_female',axis=1,inplace=True)

In [45]:
df1.columns

Index(['Name', 'Marks', 'Gender', 'half-marks'], dtype='object')

In [46]:
df1.index

RangeIndex(start=0, stop=7, step=1)

In [41]:
df1

      Name  Marks  Gender  half-marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [50]:
df1.sort_values(by=["Marks",'Gender'],ascending=False)

      Name  Marks  Gender  half-marks
2   Krisha     99  Female        49.5
6  Archana     99  Female        49.5
0  Priyang     98    Male        49.0
4   Parshv     90    Male        45.0
1   Aadhya     89  Female        44.5
3   Vedant     87    Male        43.5
5   Mittal     83  Female        41.5

In [54]:
df1[df1['Gender']=='Female'][["Name","Marks"]]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99