In [134]:
import pandas as pd
print(pd.__version__)

2.3.3

In [135]:
df=pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017         32.0          6   Rain
1  1/2/2017         35.0          7  Sunny
2  1/3/2017         28.0          2   Snow
3  1/4/2017         24.0          7   Snow
4  1/5/2017         32.0          4   Rain
5  1/6/2017         31.0          2  Sunny
6  1/7/2017          NaN          3   Rain

In [136]:
df.head()

        day  temperature  windspeed  event
0  1/1/2017         32.0          6   Rain
1  1/2/2017         35.0          7  Sunny
2  1/3/2017         28.0          2   Snow
3  1/4/2017         24.0          7   Snow
4  1/5/2017         32.0          4   Rain

In [137]:
df.tail()

        day  temperature  windspeed  event
2  1/3/2017         28.0          2   Snow
3  1/4/2017         24.0          7   Snow
4  1/5/2017         32.0          4   Rain
5  1/6/2017         31.0          2  Sunny
6  1/7/2017          NaN          3   Rain

In [138]:
df.shape

(7, 4)

In [139]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [140]:
df.head(2)

        day  temperature  windspeed  event
0  1/1/2017         32.0          6   Rain
1  1/2/2017         35.0          7  Sunny

In [141]:
df.tail(1)

        day  temperature  windspeed event
6  1/7/2017          NaN          3  Rain

In [142]:
df[2:5]

        day  temperature  windspeed event
2  1/3/2017         28.0          2  Snow
3  1/4/2017         24.0          7  Snow
4  1/5/2017         32.0          4  Rain

In [143]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
6    1/7/2017
Name: day, dtype: object

In [144]:
df.event

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
6     Rain
Name: event, dtype: object

In [145]:
type(df['event'])

pandas.core.series.Series

In [146]:
df[['event','day']]

   event       day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/6/2017
6   Rain  1/7/2017

In [147]:
df['temperature'].max()

np.float64(35.0)

In [148]:
df['temperature'].min()

np.float64(24.0)

In [149]:
df['temperature'].mean()

np.float64(30.333333333333332)

In [150]:

df.describe()

       temperature  windspeed
count     6.000000   7.000000
mean     30.333333   4.428571
std       3.829708   2.225395
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   4.000000
75%      32.000000   6.500000
max      35.000000   7.000000

In [151]:
df[df['temperature']>=32]

        day  temperature  windspeed  event
0  1/1/2017         32.0          6   Rain
1  1/2/2017         35.0          7  Sunny
4  1/5/2017         32.0          4   Rain

In [152]:
df[df['temperature']==df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017         35.0          7  Sunny

In [153]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [154]:
df

        day  temperature  windspeed  event
0  1/1/2017         32.0          6   Rain
1  1/2/2017         35.0          7  Sunny
2  1/3/2017         28.0          2   Snow
3  1/4/2017         24.0          7   Snow
4  1/5/2017         32.0          4   Rain
5  1/6/2017         31.0          2  Sunny
6  1/7/2017          NaN          3   Rain

In [155]:
df.set_index('day',inplace=True)
df

          temperature  windspeed  event
day
1/1/2017         32.0          6   Rain
1/2/2017         35.0          7  Sunny
1/3/2017         28.0          2   Snow
1/4/2017         24.0          7   Snow
1/5/2017         32.0          4   Rain
1/6/2017         31.0          2  Sunny
1/7/2017          NaN          3   Rain

In [156]:
df.reset_index(inplace=True)

In [157]:
df.set_index('event',inplace=True)
df

            day  temperature  windspeed
event
Rain   1/1/2017         32.0          6
Sunny  1/2/2017         35.0          7
Snow   1/3/2017         28.0          2
Snow   1/4/2017         24.0          7
Rain   1/5/2017         32.0          4
Sunny  1/6/2017         31.0          2
Rain   1/7/2017          NaN          3

In [158]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017         28.0          2
Snow   1/4/2017         24.0          7

In [159]:
df.reset_index(inplace=True)

In [160]:
df.iloc[0]

event              Rain
day            1/1/2017
temperature        32.0
windspeed             6
Name: 0, dtype: object

In [161]:
df[df['temperature']>=35]

   event       day  temperature  windspeed
1  Sunny  1/2/2017         35.0          7

In [162]:
df[df['event']=="Rain"]

  event       day  temperature  windspeed
0  Rain  1/1/2017         32.0          6
4  Rain  1/5/2017         32.0          4
6  Rain  1/7/2017          NaN          3

In [163]:
df.isnull()

   event    day  temperature  windspeed
0  False  False        False      False
1  False  False        False      False
2  False  False        False      False
3  False  False        False      False
4  False  False        False      False
5  False  False        False      False
6  False  False         True      False

In [164]:
df.isnull().sum()

event          0
day            0
temperature    1
windspeed      0
dtype: int64

In [165]:
df.fillna(0, inplace=True)

In [166]:
df

   event       day  temperature  windspeed
0   Rain  1/1/2017         32.0          6
1  Sunny  1/2/2017         35.0          7
2   Snow  1/3/2017         28.0          2
3   Snow  1/4/2017         24.0          7
4   Rain  1/5/2017         32.0          4
5  Sunny  1/6/2017         31.0          2
6   Rain  1/7/2017          0.0          3

In [171]:
df['temp_diff'] = df['temperature'] - df['temperature'].mean() #add new column

In [170]:
df

   event       day  temperature  windspeed  temp_diff
0   Rain  1/1/2017         32.0          6        6.0
1  Sunny  1/2/2017         35.0          7        9.0
2   Snow  1/3/2017         28.0          2        2.0
3   Snow  1/4/2017         24.0          7       -2.0
4   Rain  1/5/2017         32.0          4        6.0
5  Sunny  1/6/2017         31.0          2        5.0
6   Rain  1/7/2017          0.0          3      -26.0