### Diffrent way to create a DataFrame

In [1]:
import pandas as pd

In [12]:
#using csv file
df=pd.read_csv('weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017         32.0          6   Rain
1  1/2/2017         35.0          7  Sunny
2  1/3/2017         28.0          2   Snow
3  1/4/2017         24.0          7   Snow
4  1/5/2017         32.0          4   Rain
5  1/6/2017         31.0          2  Sunny
6  1/7/2017          NaN          3   Rain

In [3]:
#using excel file
df=pd.read_excel("weather_data.xlsx","Sheet1",engine="openpyxl")
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [7]:
#using Dictionary
data = {
    'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
    'temperature': [32, 35, 28],
    'windspeed': [6, 7, 2],
    'event': ['Rain', 'Sunny', 'Snow']
}

df = pd.DataFrame(data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [8]:
# using List of tuple
data = [
    ('1/1/2017', 32, 6, 'Rain'),
    ('1/2/2017', 35, 7, 'Sunny'),
    ('1/3/2017', 28, 2, 'Snow')
]

df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [9]:
#List of Dictionary

data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'}
]

df = pd.DataFrame(data)
print(df)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow