In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
engine = create_engine("mysql+pymysql://root:0divyesh@localhost:3306/customer")

In [17]:
df = pd.read_sql_table("customer", con=engine)
df

   cust_id cust_name   cust_city          cust_email  phonenumber  salary
0        1    ramesh  ahemedabad       ram@gmail.com          963     500
1        2    suresh       surat     sur12@yahoo.com          741     200
2        3     ronak   ahemdabad  ronak111@yahoo.com          123     300
3        4     tanvi      rajkot     tanvi@gmail.com          564     400

In [10]:
df = pd.read_sql_table("customer", con=engine,columns=["cust_id","cust_name"])
df

   cust_id cust_name
0        1   divyesh
1        2      yash
2        3     harsh

In [21]:
query='''
select * from customer where salary>=300
'''
df=pd.read_sql_query(query,engine)
df

   cust_id cust_name   cust_city          cust_email  phonenumber  salary
0        1    ramesh  ahemedabad       ram@gmail.com          963     500
1        3     ronak   ahemdabad  ronak111@yahoo.com          123     300
2        4     tanvi      rajkot     tanvi@gmail.com          564     400

In [25]:


data = {
    "cust_id": [6, 7],
    "cust_name": ["Raj Mehta", "Pooja Patel"],
    "salary": [450, 520],
    "cust_city": ["Ahmedabad", "Mumbai"]   # ✅ added column
}

new_df = pd.DataFrame(data)

new_df.to_sql("customer", con=engine, if_exists="append", index=False)

2

In [29]:
df = pd.read_sql("SELECT * FROM customer", con=engine)
df

   cust_id    cust_name   cust_city          cust_email  phonenumber  salary
0        1       ramesh  ahemedabad       ram@gmail.com        963.0     500
1        2       suresh       surat     sur12@yahoo.com        741.0     200
2        3        ronak   ahemdabad  ronak111@yahoo.com        123.0     300
3        4        tanvi      rajkot     tanvi@gmail.com        564.0     400
4        6    Raj Mehta   Ahmedabad                None          NaN     450
5        7  Pooja Patel      Mumbai                None          NaN     520