### EDA for Data Analysis

In [141]:
import pandas as pd

In [142]:
df=pd.read_csv("eda_sample_dataset.csv")
df

          Date  Age  Gender       City  Income  Expenses  Score
0   01-01-2024   18    Male  Ahmedabad   25000     15000   80.0
1   02-01-2024   20  Female      Surat   30000     18000   76.0
2   03-01-2024   22    Male   Vadodara   28000     17500   90.0
3   04-01-2024   21  Female     Rajkot   35000     22000   85.0
4   05-01-2024   23    Male  Bhavnagar   40000     26000   88.0
5   06-01-2024   24  Female  Ahmedabad   25000     15000   80.0
6   07-01-2024   25    Male      Surat   30000     18000   76.0
7   08-01-2024   22  Female   Vadodara   28000     17500   90.0
8   09-01-2024   21    Male     Rajkot   35000     22000   85.0
9   10-01-2024   26  Female  Bhavnagar   40000     26000   88.0
10  11-01-2024   18    Male  Ahmedabad   25000     15000   80.0
11  12-01-2024   20  Female      Surat   30000     18000   76.0
12  13-01-2024   22    Male   Vadodara   28000     17500   90.0
13  14-01-2024   21  Female     Rajkot   35000     22000   85.0
14  15-01-2024   23    Male  Bhavnagar   40000     26000   88.0
15  16-01-2024   24  Female  Ahmedabad   25000     15000   80.0
16  17-01-2024   25    Male      Surat   30000     18000   76.0
17  18-01-2024   22  Female   Vadodara   28000     17500   90.0
18  19-01-2024   21    Male     Rajkot   35000     22000   85.0
19  20-01-2024   26  Female  Bhavnagar   40000     26000   88.0
20  21-01-2024   18    Male  Ahmedabad   25000     15000   80.0
21  22-01-2024   20  Female      Surat   30000     18000   76.0
22  23-01-2024   22    Male   Vadodara   28000     17500   90.0
23  24-01-2024   21  Female     Rajkot   35000     22000   85.0
24  25-01-2024   23    Male  Bhavnagar   40000     26000   88.0
25  26-01-2024   24  Female  Ahmedabad   25000     15000   80.0
26  27-01-2024   25    Male      Surat   30000     18000   76.0
27  28-01-2024   22  Female   Vadodara   28000     17500   90.0
28  29-01-2024   21    Male     Rajkot   35000     22000   85.0
29  30-01-2024   26  Female  Bhavnagar   40000     26000   88.0
30  31-01-2024   18    Male  Ahmedabad   25000     15000   80.0
31  01-02-2024   20  Female      Surat   30000     18000   76.0
32  02-02-2024   22    Male   Vadodara   28000     17500   90.0
33  03-02-2024   21  Female     Rajkot   35000     22000   85.0
34  04-02-2024   23    Male  Bhavnagar   40000     26000   88.0
35  05-02-2024   24  Female  Ahmedabad   25000     15000   80.0
36  06-02-2024   25    Male      Surat   30000     18000   76.0
37  07-02-2024   22  Female   Vadodara   28000     17500   90.0
38  08-02-2024   21    Male     Rajkot   35000     22000   85.0
39  09-02-2024   26  Female  Bhavnagar   40000     26000   88.0
40  10-02-2024   18    Male  Ahmedabad   25000     15000   80.0
41  11-02-2024   20  Female      Surat   30000     18000   76.0
42  12-02-2024   22    Male   Vadodara   28000     17500   90.0
43  13-02-2024   21  Female     Rajkot   35000     22000   85.0
44  14-02-2024   23    Male  Bhavnagar   40000     26000   88.0
45  16-02-2024   25    Male      Surat   30000     18000   76.0
46  17-02-2024   22  Female   Vadodara   28000     17500   90.0
47  18-02-2024   21    Male     Rajkot   35000     22000   85.0
48  18-02-2024   21    Male     Rajkot   35000     22000   85.0

### Data Structure Understanding

In [143]:
df.head()

         Date  Age  Gender       City  Income  Expenses  Score
0  01-01-2024   18    Male  Ahmedabad   25000     15000   80.0
1  02-01-2024   20  Female      Surat   30000     18000   76.0
2  03-01-2024   22    Male   Vadodara   28000     17500   90.0
3  04-01-2024   21  Female     Rajkot   35000     22000   85.0
4  05-01-2024   23    Male  Bhavnagar   40000     26000   88.0

In [144]:
df.tail()

          Date  Age  Gender       City  Income  Expenses  Score
44  14-02-2024   23    Male  Bhavnagar   40000     26000   88.0
45  16-02-2024   25    Male      Surat   30000     18000   76.0
46  17-02-2024   22  Female   Vadodara   28000     17500   90.0
47  18-02-2024   21    Male     Rajkot   35000     22000   85.0
48  18-02-2024   21    Male     Rajkot   35000     22000   85.0

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      49 non-null     object
 1   Age       49 non-null     int64
 2   Gender    49 non-null     object
 3   City      49 non-null     object
 4   Income    49 non-null     int64
 5   Expenses  49 non-null     int64
 6   Score     49 non-null     float64
dtypes: float64(1), int64(3), object(3)
memory usage: 2.8+ KB

In [146]:
df.describe()

             Age        Income      Expenses      Score
count  49.000000     49.000000     49.000000  49.000000
mean   22.061224  31632.653061  19714.285714  83.816327
std     2.239868   5222.921746   3795.556613   5.198852
min    18.000000  25000.000000  15000.000000  76.000000
25%    21.000000  28000.000000  17500.000000  80.000000
50%    22.000000  30000.000000  18000.000000  85.000000
75%    24.000000  35000.000000  22000.000000  88.000000
max    26.000000  40000.000000  26000.000000  90.000000

In [147]:
df.shape

(49, 7)

In [148]:
df.dtypes

Date         object
Age           int64
Gender       object
City         object
Income        int64
Expenses      int64
Score       float64
dtype: object

### Data Cleaning / Quality Checks

In [149]:
df.isnull().sum()

Date        0
Age         0
Gender      0
City        0
Income      0
Expenses    0
Score       0
dtype: int64

In [150]:
df.replace(r'^\s*$', pd.NA, regex=True, inplace=True)

In [151]:
print(df.isna().sum())

Date        0
Age         0
Gender      0
City        0
Income      0
Expenses    0
Score       0
dtype: int64

In [152]:
df.dropna(inplace=True)
df

          Date  Age  Gender       City  Income  Expenses  Score
0   01-01-2024   18    Male  Ahmedabad   25000     15000   80.0
1   02-01-2024   20  Female      Surat   30000     18000   76.0
2   03-01-2024   22    Male   Vadodara   28000     17500   90.0
3   04-01-2024   21  Female     Rajkot   35000     22000   85.0
4   05-01-2024   23    Male  Bhavnagar   40000     26000   88.0
5   06-01-2024   24  Female  Ahmedabad   25000     15000   80.0
6   07-01-2024   25    Male      Surat   30000     18000   76.0
7   08-01-2024   22  Female   Vadodara   28000     17500   90.0
8   09-01-2024   21    Male     Rajkot   35000     22000   85.0
9   10-01-2024   26  Female  Bhavnagar   40000     26000   88.0
10  11-01-2024   18    Male  Ahmedabad   25000     15000   80.0
11  12-01-2024   20  Female      Surat   30000     18000   76.0
12  13-01-2024   22    Male   Vadodara   28000     17500   90.0
13  14-01-2024   21  Female     Rajkot   35000     22000   85.0
14  15-01-2024   23    Male  Bhavnagar   40000     26000   88.0
15  16-01-2024   24  Female  Ahmedabad   25000     15000   80.0
16  17-01-2024   25    Male      Surat   30000     18000   76.0
17  18-01-2024   22  Female   Vadodara   28000     17500   90.0
18  19-01-2024   21    Male     Rajkot   35000     22000   85.0
19  20-01-2024   26  Female  Bhavnagar   40000     26000   88.0
20  21-01-2024   18    Male  Ahmedabad   25000     15000   80.0
21  22-01-2024   20  Female      Surat   30000     18000   76.0
22  23-01-2024   22    Male   Vadodara   28000     17500   90.0
23  24-01-2024   21  Female     Rajkot   35000     22000   85.0
24  25-01-2024   23    Male  Bhavnagar   40000     26000   88.0
25  26-01-2024   24  Female  Ahmedabad   25000     15000   80.0
26  27-01-2024   25    Male      Surat   30000     18000   76.0
27  28-01-2024   22  Female   Vadodara   28000     17500   90.0
28  29-01-2024   21    Male     Rajkot   35000     22000   85.0
29  30-01-2024   26  Female  Bhavnagar   40000     26000   88.0
30  31-01-2024   18    Male  Ahmedabad   25000     15000   80.0
31  01-02-2024   20  Female      Surat   30000     18000   76.0
32  02-02-2024   22    Male   Vadodara   28000     17500   90.0
33  03-02-2024   21  Female     Rajkot   35000     22000   85.0
34  04-02-2024   23    Male  Bhavnagar   40000     26000   88.0
35  05-02-2024   24  Female  Ahmedabad   25000     15000   80.0
36  06-02-2024   25    Male      Surat   30000     18000   76.0
37  07-02-2024   22  Female   Vadodara   28000     17500   90.0
38  08-02-2024   21    Male     Rajkot   35000     22000   85.0
39  09-02-2024   26  Female  Bhavnagar   40000     26000   88.0
40  10-02-2024   18    Male  Ahmedabad   25000     15000   80.0
41  11-02-2024   20  Female      Surat   30000     18000   76.0
42  12-02-2024   22    Male   Vadodara   28000     17500   90.0
43  13-02-2024   21  Female     Rajkot   35000     22000   85.0
44  14-02-2024   23    Male  Bhavnagar   40000     26000   88.0
45  16-02-2024   25    Male      Surat   30000     18000   76.0
46  17-02-2024   22  Female   Vadodara   28000     17500   90.0
47  18-02-2024   21    Male     Rajkot   35000     22000   85.0
48  18-02-2024   21    Male     Rajkot   35000     22000   85.0

In [153]:
print(df.isna().sum())

Date        0
Age         0
Gender      0
City        0
Income      0
Expenses    0
Score       0
dtype: int64

In [154]:
df.to_csv("eda_sample_dataset.csv", index=False)

In [155]:
df.duplicated().sum()

np.int64(1)

In [157]:
df.drop_duplicates(inplace=True)
df

          Date  Age  Gender       City  Income  Expenses  Score
0   01-01-2024   18    Male  Ahmedabad   25000     15000   80.0
1   02-01-2024   20  Female      Surat   30000     18000   76.0
2   03-01-2024   22    Male   Vadodara   28000     17500   90.0
3   04-01-2024   21  Female     Rajkot   35000     22000   85.0
4   05-01-2024   23    Male  Bhavnagar   40000     26000   88.0
5   06-01-2024   24  Female  Ahmedabad   25000     15000   80.0
6   07-01-2024   25    Male      Surat   30000     18000   76.0
7   08-01-2024   22  Female   Vadodara   28000     17500   90.0
8   09-01-2024   21    Male     Rajkot   35000     22000   85.0
9   10-01-2024   26  Female  Bhavnagar   40000     26000   88.0
10  11-01-2024   18    Male  Ahmedabad   25000     15000   80.0
11  12-01-2024   20  Female      Surat   30000     18000   76.0
12  13-01-2024   22    Male   Vadodara   28000     17500   90.0
13  14-01-2024   21  Female     Rajkot   35000     22000   85.0
14  15-01-2024   23    Male  Bhavnagar   40000     26000   88.0
15  16-01-2024   24  Female  Ahmedabad   25000     15000   80.0
16  17-01-2024   25    Male      Surat   30000     18000   76.0
17  18-01-2024   22  Female   Vadodara   28000     17500   90.0
18  19-01-2024   21    Male     Rajkot   35000     22000   85.0
19  20-01-2024   26  Female  Bhavnagar   40000     26000   88.0
20  21-01-2024   18    Male  Ahmedabad   25000     15000   80.0
21  22-01-2024   20  Female      Surat   30000     18000   76.0
22  23-01-2024   22    Male   Vadodara   28000     17500   90.0
23  24-01-2024   21  Female     Rajkot   35000     22000   85.0
24  25-01-2024   23    Male  Bhavnagar   40000     26000   88.0
25  26-01-2024   24  Female  Ahmedabad   25000     15000   80.0
26  27-01-2024   25    Male      Surat   30000     18000   76.0
27  28-01-2024   22  Female   Vadodara   28000     17500   90.0
28  29-01-2024   21    Male     Rajkot   35000     22000   85.0
29  30-01-2024   26  Female  Bhavnagar   40000     26000   88.0
30  31-01-2024   18    Male  Ahmedabad   25000     15000   80.0
31  01-02-2024   20  Female      Surat   30000     18000   76.0
32  02-02-2024   22    Male   Vadodara   28000     17500   90.0
33  03-02-2024   21  Female     Rajkot   35000     22000   85.0
34  04-02-2024   23    Male  Bhavnagar   40000     26000   88.0
35  05-02-2024   24  Female  Ahmedabad   25000     15000   80.0
36  06-02-2024   25    Male      Surat   30000     18000   76.0
37  07-02-2024   22  Female   Vadodara   28000     17500   90.0
38  08-02-2024   21    Male     Rajkot   35000     22000   85.0
39  09-02-2024   26  Female  Bhavnagar   40000     26000   88.0
40  10-02-2024   18    Male  Ahmedabad   25000     15000   80.0
41  11-02-2024   20  Female      Surat   30000     18000   76.0
42  12-02-2024   22    Male   Vadodara   28000     17500   90.0
43  13-02-2024   21  Female     Rajkot   35000     22000   85.0
44  14-02-2024   23    Male  Bhavnagar   40000     26000   88.0
45  16-02-2024   25    Male      Surat   30000     18000   76.0
46  17-02-2024   22  Female   Vadodara   28000     17500   90.0
47  18-02-2024   21    Male     Rajkot   35000     22000   85.0

In [159]:
df['Gender'].value_counts()

Gender
Male      25
Female    23
Name: count, dtype: int64

In [161]:
df['City'].value_counts(normalize=True)

City
Surat        0.208333
Rajkot       0.208333
Vadodara     0.208333
Ahmedabad    0.187500
Bhavnagar    0.187500
Name: proportion, dtype: float64